all: k1 k2 k3 k4 k5

k1:kineone.c
	g++ -Wall -g -o k1 kineone.c -lm

k2:kinetwo.c
	g++ -Wall -g -o k2 kinetwo.c -lm

k3:kinethree.c
	g++ -Wall -g -o k3 kinethree.c -lm

k4:kinefour.c
	g++ -Wall -g -o k4 kinefour.c -lm

k5:kinefive.c
	g++ -Wall -g -o k5 kinefive.c -lm

clean:
	rm -f *.o k1 k2 k3 k4 k5
