######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 1 11:21:50 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += vectors.h
SOURCES += qt1.cpp vectors.cpp
